version: "3.8"
services: 
    web1:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
        depends_on: 
            - db
        volumes:
            - .:/railsapp
        expose: 
            - "3000"
        links:
            - db
        environment: 
            - CONT="web1"
        env_file: 
            - '.env.web'
        restart: always
       
    web2:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
        depends_on: 
            - db
            - web1
        volumes:
            - .:/railsapp
        expose: 
            - "3000"
        links:
            - db
        environment: 
            - CONT="web2"
        env_file: 
            - '.env.web'
        restart: always

    web3:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
        depends_on: 
            - db
            - web1
            - web2
        volumes:
            - .:/railsapp
        environment: 
            - CONT="web3"
        expose: 
            - "3000"
        links:
            - db
        env_file: 
            - '.env.web'
        restart: always
              
          
    db:
        image: library/mysql:5.7
        volumes: 
            - ../databasebackup/data:/var/lib/mysql
        env_file: 
            - '.env.db'
        restart: always
        expose:
            - '3306'
    
    rev_proxy:
        image: nginx:latest 
        depends_on: 
            - web1
            - web2
            - web3
            - db
        ports:
            - 8080:8080
        links:
            - web1
            - web2
            - web3
        volumes: 
            - ../revprx/nginx.conf:/etc/nginx/nginx.conf
        restart: always

